FPS = 60
ROW = 10
COLUMN = 10
CELL_SIZE_Y = 55
CELL_SIZE_X = 55
MAP_SIZE_X = CELL_SIZE_X * COLUMN
MAP_SIZE_Y = CELL_SIZE_Y * ROW
OFFSET_FROM_EDGE = 50
GAME_OVER_X = MAP_SIZE_X + OFFSET_FROM_EDGE * 2 - (MAP_SIZE_X - 400) // 2
GAME_OVER_Y = MAP_SIZE_Y + OFFSET_FROM_EDGE * 2 - (MAP_SIZE_Y - 450) // 2
BACKGROUND_SIZE_X = MAP_SIZE_X + OFFSET_FROM_EDGE * 2
BACKGROUND_SIZE_Y = MAP_SIZE_Y + OFFSET_FROM_EDGE * 2
NUMBER_OF_BOMB = 8

